# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UAVs@Berkeley
email: admin@uav.berkeley.edu
description: UAVs@Berkeley student organization on campus at Cal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
facebook: https://www.facebook.com/UAVsAtBerkeley/
youtube: https://www.youtube.com/channel/UCdf9B_VJczebLHh9TooNBdA
instagram: https://www.instagram.com/uavsatberkeley/
twitter: https://twitter.com/uavsatberkeley?lang=en
github: https://github.com/UAVs-at-Berkeley
linkedin: https://www.linkedin.com/company/uavsatberkeley/

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
